### ISSUE TITLE
[11.0] No scrollbar

### ISSUE THREAD

**Issue by satriani-vai** [senthilnathang/odoo_backend_theme#1]
Looks nice, but there are no scrollbars :)

**Comment by senthilnathang** [comment]
fixed for version 9  will be fixing it for version 11 too ;)

**Comment by hmrodrigues** [comment]
Hey @senthilnathang this still happens on V11

**Comment by teddiey** [comment]
Hi, Still no scrollbars on v11, any progress on this?

**Comment by SalahAdDin** [comment]
@senthilnathang When?

**Comment by dalbirsinghRB** [comment]
Hey @senthilnathang Great theme!  Any ETA on getting scroll bars fixed for V11?  Our project is dead in the water without it, we would love to use this theme!

**Comment by senthilnathang** [comment]
Fixed
