### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by SalahAdDin** [senthilnathang/odoo_backend_theme#7]
Other css problem:
![deepinscreenshot_seleccionar area_20180601173208](https://user-images.githubusercontent.com/5034215/40846334-f82cd7c4-65c1-11e8-9e31-d52eeb4128d9.png)
Missing icons for packages.

**Comment by senthilnathang** [comment]
you have to add icon for ur apps

**Comment by SalahAdDin** [comment]
they are `OCA` apps.

**Comment by senthilnathang** [comment]
Currently we are using font awesome icons in our theme

**Comment by senthilnathang** [comment]
Check static/src/less/menu_icons.less and add fa icons based on your module i mean menu name

**Comment by SalahAdDin** [comment]
Ok, i got it,

But, can you put it in the documentation? For all people that need it.

**Comment by senthilnathang** [comment]
Sure

**Comment by SalahAdDin** [comment]
Thanks!!!
