### ISSUE TITLE
Tooltip problem

### ISSUE THREAD

**Issue by SalahAdDin** [senthilnathang/odoo_backend_theme#8]
A problem with tooltip:
![deepinscreenshot_20180601174131](https://user-images.githubusercontent.com/5034215/40846918-9507618a-65c3-11e8-9a4f-9210c6c94d8a.png)

**Comment by senthilnathang** [comment]
fixed

**Comment by SalahAdDin** [comment]
@senthilnathang 
No, not yet:
![deepin-screen-recorder_select area_20180816163822](https://user-images.githubusercontent.com/5034215/44211997-dbc0f600-a172-11e8-9c39-567960e0fdd5.gif)
Or:
![deepin-screen-recorder_select area_20180816164722](https://user-images.githubusercontent.com/5034215/44212493-2ee77880-a174-11e8-8fb4-7dee71564629.gif)
