### ISSUE TITLE
Hey Please help to fix Scroll bar issue

### ISSUE THREAD

**Issue by ghost** [senthilnathang/odoo_backend_theme#9]
Hi Can you help me to fix scrollbar issue ?

**Comment by SalahAdDin** [comment]
@senthilnathang Please

**Comment by senthilnathang** [comment]
Fixed

**Comment by SalahAdDin** [comment]
@senthilnathang 
Not yet:
![deepin-screen-recorder_select area_20180816165718](https://user-images.githubusercontent.com/5034215/44213022-863a1880-a175-11e8-8111-788a4b97018a.gif)
![deepin-screen-recorder_select area_20180816164552](https://user-images.githubusercontent.com/5034215/44213087-981bbb80-a175-11e8-9e96-d5d0c254084b.gif)

**Comment by ghost** [comment]
> Fixed

Thanks
